### PR TITLE
updated sponsor registration form

### PR DESCRIPTION
**Pull request by mattjones315**

### CODE REVIEW

**Comment by asarnow** [comment]
@mattjones315 Do you think you could remove the .DS_store file, and not commit your altered Gemfile.lock? I can cherry pick again if not, but then you should rebase against Darrin's repo so they won't be there next time.

**Comment by mattjones315** [comment]
Yeah I'll give that a try - sorry for the hassle!

**Comment by mattjones315** [comment]
Sorry, couldn't figure out here how to uncommit the Gemfile.lock file -- will try to not commit it next time.

**Comment by asarnow** [comment]
I got the changes in cherry-pick. Maybe you should do a hard reset against the current upstream/master?

**Pull request closed without merging**
